[package]
name = "thermostat-data"
version = "0.1.0"
authors = ["Sean Bruton <sean@uberfoo.net>"]
build = "build.rs"

[dependencies]
prost = "0.4.0"
prost-derive = "0.4.0"
prost-types = "0.4.0"
bytes = "0.4.8"

[build-dependencies]
prost-build = "0.4.0"
